version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: kta-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_FEATURES: organization
    ports:
      - "8080:8080"
    command: start-dev --features=organization
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - kta-network

  kta-backend:
    build:
      context: .
      dockerfile: kta-backend/Dockerfile
    image: kta-backend
    container_name: kta-backend
    restart: unless-stopped
    ports:
      - "${KTA_BACKEND_PORT:-5001}:5001"
    volumes:
      - ./keycloak-configs:/app/keycloak-configs
      - ./scripts:/app/scripts
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KEYCLOAK_CONFIGS_REPO_PATH=/app/keycloak-configs
      - KTA_MODE=organizations
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO}
      - ORGANIZATIONS_REALM=${ORGANIZATIONS_REALM:-kta-organizations}
    depends_on:
      - keycloak
    networks:
      - kta-network

volumes:
  keycloak_data:

networks:
  kta-network:
    driver: bridge
 