services:
  - type: web
    name: kta-backend
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /health
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5001
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: KEYCLOAK_CONFIGS_REPO_PATH
        value: /app/keycloak-configs

  - type: web
    name: kta-keycloak
    runtime: docker
    dockerfilePath: ./Dockerfile.keycloak
    plan: free
    healthCheckPath: /health
    envVars:
      - key: KEYCLOAK_ADMIN
        sync: false
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: KC_DB_URL_HOST
        fromDatabase:
          name: kta-postgres
          property: host
      - key: KC_DB_URL_PORT
        fromDatabase:
          name: kta-postgres
          property: port
      - key: KC_DB_URL_DATABASE
        fromDatabase:
          name: kta-postgres
          property: database
      - key: KC_DB_USERNAME
        fromDatabase:
          name: kta-postgres
          property: username
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: kta-postgres
          property: password
      - key: KC_HOSTNAME
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: KC_HTTP_PORT
        value: 8080

databases:
  - name: kta-postgres
    plan: free
