services:
  - type: web
    name: kta-backend
    runtime: docker
    dockerfilePath: kta-backend/Dockerfile
    rootDir: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5001
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: KEYCLOAK_CONFIGS_REPO_PATH
        value: /app/keycloak-configs

  - type: web
    name: kta-keycloak
    runtime: docker
    dockerfilePath: ./Dockerfile.keycloak
    plan: free
    healthCheckPath: /health/ready
    envVars:
      - key: KEYCLOAK_ADMIN
        sync: false
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: KC_DB_URL
        sync: false
      - key: KC_DB_USERNAME
        sync: false
      - key: KC_DB_PASSWORD
        sync: false
      - key: KC_HOSTNAME
        value: kta-keycloak.onrender.com
      - key: KC_HTTP_PORT
        value: 8080
      - key: KC_HEALTH_ENABLED
        value: "true"
      - key: KC_HTTP_ENABLED
        value: "true"
      - key: KC_HOSTNAME_STRICT
        value: "false"
      - key: KC_CACHE
        value: "local"

databases:
  - name: kta-postgres
    plan: free
