name: Apply Keycloak Configuration (Local Demo)

on:
  push:
    branches:
      - main
    paths:
      - 'keycloak-configs/tenants/**.yaml'
  workflow_dispatch:
    inputs:
      tenant_file:
        description: 'Specific tenant file to apply (e.g., revolut.yaml)'
        required: false
        type: string

jobs:
  apply-config:
    runs-on: self-hosted
    steps:
      - name: Apply configuration
        shell: bash
        run: |
          #!/bin/bash
          set -e
          
          # Use the script from the actual KTA directory
          KTA_DIR="/Users/adorsys123/Desktop/dev1.1/personal/pv1/kta"
          
          # Debug info
          echo "Current directory: $(pwd)"
          echo "KTA directory exists: $(test -d "$KTA_DIR" && echo "yes" || echo "no")"
          echo "Script exists: $(test -f "$KTA_DIR/scripts/apply-config.sh" && echo "yes" || echo "no")"
          
          # Check if script exists
          if [ ! -f "$KTA_DIR/scripts/apply-config.sh" ]; then
            echo "Error: Script not found at $KTA_DIR/scripts/apply-config.sh"
            exit 1
          fi
          
          # Check script permissions
          if [ ! -x "$KTA_DIR/scripts/apply-config.sh" ]; then
            echo "Making script executable..."
            chmod +x "$KTA_DIR/scripts/apply-config.sh"
          fi
          
          # Get tenant file from input
          TENANT_FILE="${{ github.event.inputs.tenant_file }}"
          echo "Tenant file: '$TENANT_FILE'"
          
          # Apply configuration
          if [ -n "$TENANT_FILE" ]; then
            echo "Applying specific file: $TENANT_FILE"
            "$KTA_DIR/scripts/apply-config.sh" "$TENANT_FILE"
          else
            echo "Applying all files"
            "$KTA_DIR/scripts/apply-config.sh"
          fi
          
          # Done
          echo "Configuration applied successfully!" 