name: Apply Keycloak Configuration (Local Demo)

on:
  push:
    branches:
      - main
    paths:
      - 'keycloak-configs/tenants/**.yaml'
  workflow_dispatch:
    inputs:
      tenant_file:
        description: 'Specific tenant file to apply (e.g., revolut.yaml)'
        required: false
        type: string

jobs:
  apply-config:
    runs-on: self-hosted  # Uses local runner
    steps:
      - name: Apply configuration
        run: |
          # Use the script from the actual KTA directory
          KTA_DIR="/Users/adorsys123/Desktop/dev1.1/personal/pv1/kta"
          
          if [ -n "${{ github.event.inputs.tenant_file }}" ]; then
            # Apply specific file
            "$KTA_DIR/scripts/apply-config.sh" "${{ github.event.inputs.tenant_file }}"
          else
            # Apply all files
            "$KTA_DIR/scripts/apply-config.sh" 